% -------------------------------------------------------------------
%  Generated by MATLAB on 27-Sep-2022 15:09:07
%  MATLAB version: 9.3.0.713579 (R2017b)
% -------------------------------------------------------------------
saveVarsMat = load('myfun_fsolve_script.mat');

fun = saveVarsMat.fun; % <1x1 function_handle> unsupported class

fval = [-1.8516743693908211E-11 7.1196382123162039E-12];

x = [1.9999999999965885 3.0000000000026819];

x0 = [0 0];

clear saveVarsMat;
